import { chromium } from 'playwright';
import fs from 'fs';
const U='http://localhost:8774/index.html';
const d=process.env.HOME+'/.cache/ms-playwright/chromium_headless_shell-1243/';
const exe=d+fs.readdirSync(d).find(x=>x.startsWith('chrome'))+'/chrome-headless-shell';
const b=await chromium.launch({executablePath:exe});
const ctx=await b.newContext({viewport:{width:412,height:915},serviceWorkers:'allow'});
const p=await ctx.newPage();const errs=[];p.on('pageerror',e=>errs.push(e.message));
await p.route(/fonts\.(googleapis|gstatic)/,r=>r.abort());
await p.goto(U);await p.waitForTimeout(3000);
const info=await p.evaluate(async()=>({keys:await caches.keys(),sw:!!(await navigator.serviceWorker.getRegistration()),n:(await (await caches.open((await caches.keys())[0])).keys()).length,manifest:!!document.querySelector('link[rel=manifest]')}));
console.log('SW installed:',JSON.stringify(info));
await p.reload();await p.waitForTimeout(1500);
await ctx.setOffline(true);
await p.reload();await p.waitForTimeout(1800);
const off=await p.evaluate(()=>({title:document.title,items:document.querySelectorAll('.ev-row,.ev-item,[data-act="check"]').length,h:document.body.innerText.slice(0,40)}));
console.log('OFFLINE reload ok:',JSON.stringify(off));
await ctx.setOffline(false);
const m=await p.evaluate(async()=>{const r=await fetch('manifest.webmanifest');return r.json()});
console.log('manifest:',m.name,m.display,m.start_url,(m.icons||[]).length+' icons');
console.log('errors',errs.length,errs.slice(0,2));
await b.close();
